// Code generated by build/generate-golang.js; DO NOT EDIT.
package connection

func (*Connection) EventCategory() string {
	return "connection"
}

func (*MesheryInstance) EventCategory() string {
	return "connection"
}
