// Package keychain provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package keychain

import (
	corev1alpha1 "github.com/meshery/schemas/models/v1alpha1/core"
)

// Keychain Represents a collection of keys.
type Keychain struct {
	// Id A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	ID corev1alpha1.Uuid `db:"id" json:"id" yaml:"id"`

	// Name Name of the keychain.
	Name string `db:"name" json:"name" yaml:"name"`

	// Owner A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
	Owner corev1alpha1.Uuid `db:"owner" json:"owner" yaml:"owner"`

	// CreatedAt Timestamp when the resource was created.
	CreatedAt corev1alpha1.CreatedAt `db:"created_at" json:"created_at" yaml:"created_at"`

	// UpdatedAt Timestamp when the resource was updated.
	UpdatedAt corev1alpha1.UpdatedAt `db:"updated_at" json:"updated_at" yaml:"updated_at"`

	// DeletedAt SQL null Timestamp to handle null values of time.
	DeletedAt corev1alpha1.NullTime `db:"deleted_at" json:"deleted_at,omitempty" yaml:"deleted_at,omitempty"`
}

// KeychainPage defines model for KeychainPage.
type KeychainPage struct {
	Page       corev1alpha1.Number `json:"page" yaml:"page"`
	PageSize   corev1alpha1.Number `json:"page_size" yaml:"page_size"`
	TotalCount corev1alpha1.Number `json:"total_count" yaml:"total_count"`
	Keychains  []struct {
		// Id A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
		Id corev1alpha1.Uuid `json:"id" yaml:"id"`

		// Name Name of the keychain.
		Name string `db:"name" json:"name" yaml:"name"`

		// Owner A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
		Owner corev1alpha1.Uuid `json:"owner" yaml:"owner"`

		// CreatedAt Timestamp when the resource was created.
		CreatedAt corev1alpha1.CreatedAt `db:"created_at" json:"created_at" yaml:"created_at"`

		// UpdatedAt Timestamp when the resource was updated.
		UpdatedAt corev1alpha1.UpdatedAt `db:"updated_at" json:"updated_at" yaml:"updated_at"`

		// DeletedAt SQL null Timestamp to handle null values of time.
		DeletedAt corev1alpha1.NullTime `json:"deleted_at,omitempty" yaml:"deleted_at,omitempty"`
	} `json:"keychains" yaml:"keychains"`
}

// KeyId A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
type KeyId = corev1alpha1.Uuid

// KeychainId A Universally Unique Identifier used to uniquely identify entities in Meshery. The UUID core definition is used across different schemas.
type KeychainId = corev1alpha1.Uuid

// Corev1alpha1Order defines model for order.
type Corev1alpha1Order = string

// Corev1alpha1Page defines model for page.
type Corev1alpha1Page = string

// Corev1alpha1Pagesize defines model for pagesize.
type Corev1alpha1Pagesize = string

// Corev1alpha1Search defines model for search.
type Corev1alpha1Search = string
