// Code generated by build/generate-golang.js; DO NOT EDIT.
package organization

import (
	"database/sql/driver"
	"encoding/json"
	"github.com/meshery/meshkit/utils"
)

func (value *OrgMetadata) Scan(src interface{}) error {
	if src == nil {
		*value = OrgMetadata{}
		return nil
	}

	data, err := utils.Cast[[]byte](src)
	if err != nil {
		return err
	}

	if err := json.Unmarshal(data, value); err != nil {
		return utils.ErrUnmarshal(err)
	}

	return nil
}

func (value OrgMetadata) Value() (driver.Value, error) {
	marshaledValue, err := json.Marshal(value)
	if err != nil {
		return nil, utils.ErrMarshal(err)
	}

	return marshaledValue, nil
}

func (*Organization) EventCategory() string {
	return "organization"
}
